;
; generated by AheadLibEx (Rust) - x64 jump table
;
; Author: i1tao
; Blog: https://www.winsec.cn
; Github: https://github.com/i1tao/AheadLibEx

.DATA
EXTERN pfnAheadLibEx_GetFileVersionInfoA:dq;
EXTERN pfnAheadLibEx_GetFileVersionInfoByHandle:dq;
EXTERN pfnAheadLibEx_GetFileVersionInfoExA:dq;
EXTERN pfnAheadLibEx_GetFileVersionInfoExW:dq;
EXTERN pfnAheadLibEx_GetFileVersionInfoSizeA:dq;
EXTERN pfnAheadLibEx_GetFileVersionInfoSizeExA:dq;
EXTERN pfnAheadLibEx_GetFileVersionInfoSizeExW:dq;
EXTERN pfnAheadLibEx_GetFileVersionInfoSizeW:dq;
EXTERN pfnAheadLibEx_GetFileVersionInfoW:dq;
EXTERN pfnAheadLibEx_VerFindFileA:dq;
EXTERN pfnAheadLibEx_VerFindFileW:dq;
EXTERN pfnAheadLibEx_VerInstallFileA:dq;
EXTERN pfnAheadLibEx_VerInstallFileW:dq;
EXTERN pfnAheadLibEx_VerLanguageNameA:dq;
EXTERN pfnAheadLibEx_VerLanguageNameW:dq;
EXTERN pfnAheadLibEx_VerQueryValueA:dq;
EXTERN pfnAheadLibEx_VerQueryValueW:dq;

.CODE
AheadLibEx_GetFileVersionInfoA PROC
    jmp pfnAheadLibEx_GetFileVersionInfoA
AheadLibEx_GetFileVersionInfoA ENDP

AheadLibEx_GetFileVersionInfoByHandle PROC
    jmp pfnAheadLibEx_GetFileVersionInfoByHandle
AheadLibEx_GetFileVersionInfoByHandle ENDP

AheadLibEx_GetFileVersionInfoExA PROC
    jmp pfnAheadLibEx_GetFileVersionInfoExA
AheadLibEx_GetFileVersionInfoExA ENDP

AheadLibEx_GetFileVersionInfoExW PROC
    jmp pfnAheadLibEx_GetFileVersionInfoExW
AheadLibEx_GetFileVersionInfoExW ENDP

AheadLibEx_GetFileVersionInfoSizeA PROC
    jmp pfnAheadLibEx_GetFileVersionInfoSizeA
AheadLibEx_GetFileVersionInfoSizeA ENDP

AheadLibEx_GetFileVersionInfoSizeExA PROC
    jmp pfnAheadLibEx_GetFileVersionInfoSizeExA
AheadLibEx_GetFileVersionInfoSizeExA ENDP

AheadLibEx_GetFileVersionInfoSizeExW PROC
    jmp pfnAheadLibEx_GetFileVersionInfoSizeExW
AheadLibEx_GetFileVersionInfoSizeExW ENDP

AheadLibEx_GetFileVersionInfoSizeW PROC
    jmp pfnAheadLibEx_GetFileVersionInfoSizeW
AheadLibEx_GetFileVersionInfoSizeW ENDP

AheadLibEx_GetFileVersionInfoW PROC
    jmp pfnAheadLibEx_GetFileVersionInfoW
AheadLibEx_GetFileVersionInfoW ENDP

AheadLibEx_VerFindFileA PROC
    jmp pfnAheadLibEx_VerFindFileA
AheadLibEx_VerFindFileA ENDP

AheadLibEx_VerFindFileW PROC
    jmp pfnAheadLibEx_VerFindFileW
AheadLibEx_VerFindFileW ENDP

AheadLibEx_VerInstallFileA PROC
    jmp pfnAheadLibEx_VerInstallFileA
AheadLibEx_VerInstallFileA ENDP

AheadLibEx_VerInstallFileW PROC
    jmp pfnAheadLibEx_VerInstallFileW
AheadLibEx_VerInstallFileW ENDP

AheadLibEx_VerLanguageNameA PROC
    jmp pfnAheadLibEx_VerLanguageNameA
AheadLibEx_VerLanguageNameA ENDP

AheadLibEx_VerLanguageNameW PROC
    jmp pfnAheadLibEx_VerLanguageNameW
AheadLibEx_VerLanguageNameW ENDP

AheadLibEx_VerQueryValueA PROC
    jmp pfnAheadLibEx_VerQueryValueA
AheadLibEx_VerQueryValueA ENDP

AheadLibEx_VerQueryValueW PROC
    jmp pfnAheadLibEx_VerQueryValueW
AheadLibEx_VerQueryValueW ENDP


END
