// generated by AheadLibEx (Rust) - only x64
// Author: i1tao
// Blog: https://www.winsec.cn
// Github: https://github.com/i1tao/AheadLibEx

// Auto proxy for version.dll

#include <windows.h>
#include "MemoryKit.h"

#ifdef UNREFERENCED_PARAMETER
#undef UNREFERENCED_PARAMETER
#endif
#define UNREFERENCED_PARAMETER(P) (void)(P)

#pragma comment(linker, "/EXPORT:\"GetFileVersionInfoA=AheadLibEx_GetFileVersionInfoA,@1\"")
#pragma comment(linker, "/EXPORT:\"GetFileVersionInfoByHandle=AheadLibEx_GetFileVersionInfoByHandle,@2\"")
#pragma comment(linker, "/EXPORT:\"GetFileVersionInfoExA=AheadLibEx_GetFileVersionInfoExA,@3\"")
#pragma comment(linker, "/EXPORT:\"GetFileVersionInfoExW=AheadLibEx_GetFileVersionInfoExW,@4\"")
#pragma comment(linker, "/EXPORT:\"GetFileVersionInfoSizeA=AheadLibEx_GetFileVersionInfoSizeA,@5\"")
#pragma comment(linker, "/EXPORT:\"GetFileVersionInfoSizeExA=AheadLibEx_GetFileVersionInfoSizeExA,@6\"")
#pragma comment(linker, "/EXPORT:\"GetFileVersionInfoSizeExW=AheadLibEx_GetFileVersionInfoSizeExW,@7\"")
#pragma comment(linker, "/EXPORT:\"GetFileVersionInfoSizeW=AheadLibEx_GetFileVersionInfoSizeW,@8\"")
#pragma comment(linker, "/EXPORT:\"GetFileVersionInfoW=AheadLibEx_GetFileVersionInfoW,@9\"")
#pragma comment(linker, "/EXPORT:\"VerFindFileA=AheadLibEx_VerFindFileA,@10\"")
#pragma comment(linker, "/EXPORT:\"VerFindFileW=AheadLibEx_VerFindFileW,@11\"")
#pragma comment(linker, "/EXPORT:\"VerInstallFileA=AheadLibEx_VerInstallFileA,@12\"")
#pragma comment(linker, "/EXPORT:\"VerInstallFileW=AheadLibEx_VerInstallFileW,@13\"")
#pragma comment(linker, "/EXPORT:\"VerLanguageNameA=AheadLibEx_VerLanguageNameA,@14\"")
#pragma comment(linker, "/EXPORT:\"VerLanguageNameW=AheadLibEx_VerLanguageNameW,@15\"")
#pragma comment(linker, "/EXPORT:\"VerQueryValueA=AheadLibEx_VerQueryValueA,@16\"")
#pragma comment(linker, "/EXPORT:\"VerQueryValueW=AheadLibEx_VerQueryValueW,@17\"")


#ifdef __cplusplus
#define AHEADLIB_EXTERN extern "C"
#else
#define AHEADLIB_EXTERN
#endif

#ifdef __cplusplus
extern "C" {
#endif
PVOID pfnAheadLibEx_GetFileVersionInfoA = NULL;
PVOID pfnAheadLibEx_GetFileVersionInfoByHandle = NULL;
PVOID pfnAheadLibEx_GetFileVersionInfoExA = NULL;
PVOID pfnAheadLibEx_GetFileVersionInfoExW = NULL;
PVOID pfnAheadLibEx_GetFileVersionInfoSizeA = NULL;
PVOID pfnAheadLibEx_GetFileVersionInfoSizeExA = NULL;
PVOID pfnAheadLibEx_GetFileVersionInfoSizeExW = NULL;
PVOID pfnAheadLibEx_GetFileVersionInfoSizeW = NULL;
PVOID pfnAheadLibEx_GetFileVersionInfoW = NULL;
PVOID pfnAheadLibEx_VerFindFileA = NULL;
PVOID pfnAheadLibEx_VerFindFileW = NULL;
PVOID pfnAheadLibEx_VerInstallFileA = NULL;
PVOID pfnAheadLibEx_VerInstallFileW = NULL;
PVOID pfnAheadLibEx_VerLanguageNameA = NULL;
PVOID pfnAheadLibEx_VerLanguageNameW = NULL;
PVOID pfnAheadLibEx_VerQueryValueA = NULL;
PVOID pfnAheadLibEx_VerQueryValueW = NULL;
#ifdef __cplusplus
}
#endif


#undef AHEADLIB_EXTERN

static HMODULE g_origin_module_handle;

static VOID WINAPI free_origin_module(void)
{
    if (g_origin_module_handle)
    {
        FreeLibrary(g_origin_module_handle);
        g_origin_module_handle = NULL;
    }
}

static BOOL WINAPI load_original_module(HMODULE module)
{
    TCHAR module_path[MAX_PATH] = { 0 };
    TCHAR message[MAX_PATH] = { 0 };

    UNREFERENCED_PARAMETER(module);

    GetSystemDirectory(module_path, MAX_PATH);
    lstrcat(module_path, TEXT("\\"));
    lstrcat(module_path, TEXT("version.dll"));

    g_origin_module_handle = LoadLibrary(module_path);
    if (!g_origin_module_handle)
    {
        wsprintf(message, TEXT("Cannot locate %s, AheadLibEx cannot continue.\\nerror code:0x%08X"), module_path, GetLastError());
        MessageBox(NULL, message, TEXT("AheadLibEx"), MB_ICONSTOP);
    }

    return g_origin_module_handle != NULL;

}

static FARPROC WINAPI get_address(PCSTR proc_name)
{
    CHAR ordinal_name[64];
    TCHAR message[MAX_PATH];
    FARPROC address = GetProcAddress(g_origin_module_handle, proc_name);
    if (!address)
    {
        if (HIWORD(proc_name) == 0)
        {
            wsprintfA(ordinal_name, "#%d", proc_name);
            proc_name = ordinal_name;
        }
        wsprintf(message, TEXT("Cannot locate export %hs."), proc_name);
        MessageBox(NULL, message, TEXT("AheadLibEx"), MB_ICONSTOP);

        ExitProcess(0);
    }
    return address;
}

static VOID WINAPI init_forwarders(void)
{
    pfnAheadLibEx_GetFileVersionInfoA = get_address("GetFileVersionInfoA");
    pfnAheadLibEx_GetFileVersionInfoByHandle = get_address("GetFileVersionInfoByHandle");
    pfnAheadLibEx_GetFileVersionInfoExA = get_address("GetFileVersionInfoExA");
    pfnAheadLibEx_GetFileVersionInfoExW = get_address("GetFileVersionInfoExW");
    pfnAheadLibEx_GetFileVersionInfoSizeA = get_address("GetFileVersionInfoSizeA");
    pfnAheadLibEx_GetFileVersionInfoSizeExA = get_address("GetFileVersionInfoSizeExA");
    pfnAheadLibEx_GetFileVersionInfoSizeExW = get_address("GetFileVersionInfoSizeExW");
    pfnAheadLibEx_GetFileVersionInfoSizeW = get_address("GetFileVersionInfoSizeW");
    pfnAheadLibEx_GetFileVersionInfoW = get_address("GetFileVersionInfoW");
    pfnAheadLibEx_VerFindFileA = get_address("VerFindFileA");
    pfnAheadLibEx_VerFindFileW = get_address("VerFindFileW");
    pfnAheadLibEx_VerInstallFileA = get_address("VerInstallFileA");
    pfnAheadLibEx_VerInstallFileW = get_address("VerInstallFileW");
    pfnAheadLibEx_VerLanguageNameA = get_address("VerLanguageNameA");
    pfnAheadLibEx_VerLanguageNameW = get_address("VerLanguageNameW");
    pfnAheadLibEx_VerQueryValueA = get_address("VerQueryValueA");
    pfnAheadLibEx_VerQueryValueW = get_address("VerQueryValueW");

}

DWORD WINAPI patch_thread_proc(LPVOID context)
{
    UNREFERENCED_PARAMETER(context);
	
	HWND hwnd;
	while ((hwnd = FindWindowW(L"FLUTTER_RUNNER_WIN32_WINDOW", L"Rive")) == NULL)
	{
		Sleep(500);
	}
	
    MemoryKitScanResult result =
        MemoryKit_FindPattern("48 8B 45 C8 48 89 55 C0 A8 10 0F 85 ?? ?? ?? ?? 48 8B 7D D8 8B 4F FF");
		
	if (!MemoryKit_Found(result)) {
		return 1;
	}
		
	result = MemoryKit_Offset(result, 10);
	const uintptr_t address = MemoryKit_Address(result);
	
    if (!MemoryKit_Patch(address, "90 90 90 90 90 90")) {
        return 1;
    }
    return 0;
}

BOOL APIENTRY DllMain(HMODULE module, DWORD reason, PVOID reserved)
{
    UNREFERENCED_PARAMETER(reserved);
    if (reason == DLL_PROCESS_ATTACH)
    {
        DisableThreadLibraryCalls(module);
        if (!load_original_module(module))
        {
            return FALSE;
        }
        init_forwarders();

        HANDLE thread = CreateThread(NULL, 0, patch_thread_proc, NULL, 0, NULL);
        if (thread)
        {
            CloseHandle(thread);
        }
    }
    else if (reason == DLL_PROCESS_DETACH)
    {
        free_origin_module();
    }
    return TRUE;
}
